### ISSUE TITLE
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)

### ISSUE THREAD

**Issue by soam-abhishek** [vimeo/vimeo.py#121]
```
Traceback (most recent call last):
  File "code.py", line 1, in <module>
    import vimeo
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/vimeo/__init__.py", line 8, in <module>
    from .client import VimeoClient
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/vimeo/client.py", line 11, in <module>
    from .upload import UploadMixin
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/vimeo/upload.py", line 9, in <module>
    from tusclient import client
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/tusclient/client.py", line 1, in <module>
    from tusclient.uploader import Uploader
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/tusclient/uploader.py", line 12, in <module>
    from tusclient.request import TusRequest
  File "/Users/abhishek/Desktop/vision/vimeo/env/lib/python2.7/site-packages/tusclient/request.py", line 1, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
```

**Comment by erunion** [comment]
This looks to be an issue in some environments with tus-py-client.

Do you mind trying the steps that appear to have solved the problem in the Transloadit library? https://github.com/transloadit/python-sdk/issues/4#issuecomment-346785159

**Comment by soam-abhishek** [comment]
Thanks for helping out.
