### ISSUE TITLE
Release 1.0.10 is broken because of a missing README.md in the package

### ISSUE THREAD

**Issue by seirl** [vimeo/vimeo.py#139]
Traceback:

```
Collecting pyvimeo (from -r requirements.txt (line 70))
  Using cached https://files.pythonhosted.org/packages/5b/4e/7ced00ae0843e97c0679b1ac15c88f638c38c8eeef7d44b54db8b2b72b44/PyVimeo-1.0.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5v3dg5s7/pyvimeo/setup.py", line 9, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5v3dg5s7/pyvimeo/
```

**Comment by erunion** [comment]
Well that's an interesting one. I've reverted the two lines I added to `setup.py` for the README stuff so we could get a better description on PyPI.

1.0.11 should be good.

**Comment by seirl** [comment]
Thanks a lot for the quick fix, I can confirm it works now.
