### ISSUE TITLE
unable to import module

### ISSUE THREAD

**Issue by madcodingrocks** [vimeo/vimeo.py#154]
Hi, when I import vimeo I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mad/.local/lib/python2.7/site-packages/vimeo/__init__.py", line 8, in <module>
    from .client import VimeoClient
  File "/home/mad/.local/lib/python2.7/site-packages/vimeo/client.py", line 11, in <module>
    from .upload import UploadMixin
  File "/home/mad/.local/lib/python2.7/site-packages/vimeo/upload.py", line 9, in <module>
    from . import exceptions
ImportError: cannot import name exceptions
```
Im using Python 2.7
any Idea why is that happening?
thanks in advance!

**Comment by jaylinski** [comment]
Does this still happen with the latest version?

**Comment by Bezarius** [comment]
pyvimeo doesn't support python 2.7
