### ISSUE TITLE
I try to upload a video got error "ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed" 

### ISSUE THREAD

**Issue by kartikdanidhariya** [vimeo/vimeo.py#163]
```Traceback (most recent call last):
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/upload.py", line 150, in __perform_tus_upload
    uploader.upload()
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/tusclient/uploader.py", line 289, in upload
    self.upload_chunk()
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/tusclient/uploader.py", line 299, in upload_chunk
    self._do_request()
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/tusclient/uploader.py", line 310, in _do_request
    self.request.perform()
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/tusclient/request.py", line 84, in perform
    raise e
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/tusclient/request.py", line 73, in perform
    self.handle.request("PATCH", path, chunk, self._request_headers)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1028, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 968, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1432, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/edvay/edvay/edvay/tasks.py", line 367, in upload_video_to_vimeo
    video_url = vimeo_obj.upload(dw_file, data={'name': dw_file, 'description': key})
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/upload.py", line 71, in upload
    return self.__perform_tus_upload(filename, attempt, chunk_size=chunk_size)
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/upload.py", line 154, in __perform_tus_upload
    'Unexpected error when uploading through tus.'
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/exceptions.py", line 93, in __init__
    super().__init__(response, message)
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/exceptions.py", line 30, in __init__
    self.message = self.__get_message(response)
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/vimeo/exceptions.py", line 23, in __get_message
    message = getattr(response, 'message')
AttributeError: 'SSLCertVerificationError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/apple/.local/share/virtualenvs/edvay-ZAZVItV1/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/apple/edvay/edvay/edvay/tasks.py", line 398, in upload_video_to_vimeo
    print('Server reported: %s' % e.message)
AttributeError: 'AttributeError' object has no attribute 'message'```

**Comment by jaylinski** [comment]
Your logs indicate that you are running Python on macOS. A quick Google search for your issue turned up the following solution:

https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

Did you try this?
