### ISSUE TITLE
assert ticket.status_code == 201, "Failed to create an upload ticket"

### ISSUE THREAD

**Issue by radavis** [vimeo/vimeo.py#60]
I'm attempting to upload a video to my Vimeo account. I have created an access token from the Vimeo API page.

```
# requirements.txt
--index-url https://pypi.python.org/simple/

python-dotenv==0.1.2
PyVimeo==0.2.1
```

```
import os
import dotenv

dotenv_path = os.path.join(os.path.dirname(__file__), '.env')
dotenv.load_dotenv(dotenv_path)

import vimeo

v = vimeo.VimeoClient(
    token = os.environ.get("VIMEO_ACCESS_TOKEN"),
    key = os.environ.get("VIMEO_CLIENT_ID"),
    secret = os.environ.get("VIMEO_CLIENT_SECRET")
)

about_me = v.get('/me')
assert about_me.status_code == 200

video_uri = v.upload('small.mp4')
```

```
Traceback (most recent call last):
  File "upload.py", line 18, in <module>
    video_uri = v.upload('small.mp4')
  File "/Users/rd/.pyenv/versions/3.4.3/lib/python3.4/site-packages/vimeo/upload.py", line 22, in upload
    return self._perform_upload(filename, ticket)
  File "/Users/rd/.pyenv/versions/3.4.3/lib/python3.4/site-packages/vimeo/upload.py", line 37, in _perform_upload
    assert ticket.status_code == 201, "Failed to create an upload ticket"
AssertionError: Failed to create an upload ticket
```

**Comment by radavis** [comment]
This issue was resolved when I updated my requirements.txt to `PyVimeo>=0.2.1`, and ran  `pip install -r requirements.txt --upgrade`

PyVimeo was updated to 0.3.0.

**Comment by harishtm** [comment]
Hi,

I am getting an error 
about_me = v.get('/me')
about_me.json()

JSONDecodeError at /viedo-upload/

Expecting value: line 1 column 1 (char 0)

Could any one help
