### ISSUE TITLE
Fail to install by pip

### ISSUE THREAD

**Issue by luis-kaufmann-silva** [vimeo/vimeo.py#66]
I'm running the command below on a vagrant machine (with debian powered)
```shell
(MY_ENV)vagrant@machine:/srv/www/<MY_PROJECT>$ pip install PyVimeo
Downloading/unpacking PyVimeo
  Downloading PyVimeo-0.3.0.macosx-10.10-intel.tar.gz
  Running setup.py egg_info for package PyVimeo
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/srv/env/<MY_PROJECT>/build/PyVimeo/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/srv/env/<MY_PROJECT>/build/PyVimeo/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /srv/env/<MY_PROJECT>/build/PyVimeo
Storing complete log in /home/vagrant/.pip/pip.log
```
But, if i run this command:
```shell
pip install https://github.com/vimeo/vimeo.py/archive/master.zip
``` 
it's works fine.

**Comment by greedo** [comment]
@luis-kaufmann-silva I suspect their may be an issue with the version of `pip` you are using.

If you do
```
pip install -v PyVimeo
```
Pip will give you a bit more information about exactly what it is doing. You would see any pip errors in the more verbose output. Let you know what you get from the verbose output.

**Comment by luis-kaufmann-silva** [comment]
A bit more of logs:

```shell
(test)vagrant@machine:~$ pip install -v PyVimeo
Downloading/unpacking PyVimeo
  Using version 0.3.0.macosx-10.10-intel (newest of versions: 0.3.0.macosx-10.10-intel, 0.2.1, 0.2.0, 0.1.1)
  Downloading PyVimeo-0.3.0.macosx-10.10-intel.tar.gz
  Running setup.py egg_info for package PyVimeo
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/srv/env/test/build/PyVimeo/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/srv/env/test/build/PyVimeo/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /srv/env/test/build/PyVimeo
Exception information:
Traceback (most recent call last):
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /srv/env/test/build/PyVimeo

Storing complete log in /home/vagrant/.pip/pip.log
(test)vagrant@machine:~$ cat ~/.pip/pip.log 
------------------------------------------------------------
/srv/env/test/bin/pip run on Thu Jul 23 05:16:10 2015
Downloading/unpacking PyVimeo

  Getting page http://pypi.python.org/simple/PyVimeo
  URLs to search for versions for PyVimeo:
  * http://pypi.python.org/simple/PyVimeo/
  Getting page http://pypi.python.org/simple/PyVimeo/
  Analyzing links from page https://pypi.python.org/simple/pyvimeo/
    Skipping link https://pypi.python.org/packages/2.7/P/PyVimeo/PyVimeo-0.1.0-py2.7.egg#md5=8de3aecf85cae5817f2054c8c0b51de6 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/py2/P/PyVimeo/PyVimeo-0.2.1-py2-none-any.whl#md5=9406e75c5eb129cba3d7b69f72a291f0 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py2/P/PyVimeo/PyVimeo-0.3.0-py2-none-any.whl#md5=db329f9d98a5dfd6e8fbeafa8d3604d4 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py3/P/PyVimeo/PyVimeo-0.2.1-py3-none-any.whl#md5=8babb1ef0e4705b999366cdb0c818069 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py3/P/PyVimeo/PyVimeo-0.3.0-py3-none-any.whl#md5=933da4e17c145c734b901b594ed326fb (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Found link https://pypi.python.org/packages/source/P/PyVimeo/PyVimeo-0.1.1.tar.gz#md5=be1f4142ca10fd96910ad9c3738d009a (from https://pypi.python.org/simple/pyvimeo/), version: 0.1.1
    Found link https://pypi.python.org/packages/source/P/PyVimeo/PyVimeo-0.2.0.tar.gz#md5=e52e4be7bfedc2adcebe1c8c10279b65 (from https://pypi.python.org/simple/pyvimeo/), version: 0.2.0
    Found link https://pypi.python.org/packages/source/P/PyVimeo/PyVimeo-0.2.1.tar.gz#md5=93b7864ef68767156895a98f86491c3d (from https://pypi.python.org/simple/pyvimeo/), version: 0.2.1
    Found link https://pypi.python.org/packages/source/P/PyVimeo/PyVimeo-0.3.0.macosx-10.10-intel.tar.gz#md5=0f07813a2787f41f151f79e811d7488f (from https://pypi.python.org/simple/pyvimeo/), version: 0.3.0.macosx-10.10-intel
  Using version 0.3.0.macosx-10.10-intel (newest of versions: 0.3.0.macosx-10.10-intel, 0.2.1, 0.2.0, 0.1.1)

  Downloading PyVimeo-0.3.0.macosx-10.10-intel.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/P/PyVimeo/PyVimeo-0.3.0.macosx-10.10-intel.tar.gz#md5=0f07813a2787f41f151f79e811d7488f (from https://pypi.python.org/simple/pyvimeo/)
  Running setup.py egg_info for package PyVimeo

    Traceback (most recent call last):

      File "<string>", line 14, in <module>

    IOError: [Errno 2] No such file or directory: '/srv/env/test/build/PyVimeo/setup.py'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 14, in <module>

IOError: [Errno 2] No such file or directory: '/srv/env/test/build/PyVimeo/setup.py'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /srv/env/test/build/PyVimeo

Exception information:
Traceback (most recent call last):
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 1009, in prepare_files
    req_to_install.run_egg_info()
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 225, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/srv/env/test/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 256, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /srv/env/test/build/PyVimeo

```

See the line "Downloading PyVimeo-0.3.0.macosx-10.10-intel.tar.gz", i'm using a debian based machine. It's right?

Thanks in advance ;)

**Comment by greedo** [comment]
@luis-kaufmann-silva looking at the way pip is resolving links it is skipping .whl

```
 Analyzing links from page https://pypi.python.org/simple/pyvimeo/
    Skipping link https://pypi.python.org/packages/2.7/P/PyVimeo/PyVimeo-0.1.0-py2.7.egg#md5=8de3aecf85cae5817f2054c8c0b51de6 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .egg
    Skipping link https://pypi.python.org/packages/py2/P/PyVimeo/PyVimeo-0.2.1-py2-none-any.whl#md5=9406e75c5eb129cba3d7b69f72a291f0 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py2/P/PyVimeo/PyVimeo-0.3.0-py2-none-any.whl#md5=db329f9d98a5dfd6e8fbeafa8d3604d4 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py3/P/PyVimeo/PyVimeo-0.2.1-py3-none-any.whl#md5=8babb1ef0e4705b999366cdb0c818069 (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
    Skipping link https://pypi.python.org/packages/py3/P/PyVimeo/PyVimeo-0.3.0-py3-none-any.whl#md5=933da4e17c145c734b901b594ed326fb (from https://pypi.python.org/simple/pyvimeo/); unknown archive format: .whl
```

Meaning you most likely do not have [wheel](https://pypi.python.org/pypi/wheel) installed. Pip is attempting to install `PyVimeo-0.3.0.macosx-10.10-intel.tar.gz` which you do not want. You will need to install wheel and then pip will install the wheel version of PyVimeo by default, which

- Avoids setup.py
- Allows for more consistent installs across platforms and machines

Let me know if that works for you.

**Comment by luis-kaufmann-silva** [comment]
Upgrading setuptools the problem is solved. This link helped me http://stackoverflow.com/questions/20950295/pip-install-error-unknown-archive-format-whl

For me, the problem has been solved. Thanks you very much for your help ;)

**Comment by greedo** [comment]
Excellent!
