### ISSUE TITLE
AttributeError : Cannot found 'VimeoClient' obejct

### ISSUE THREAD

**Issue by khs8727** [vimeo/vimeo.py#90]
I've play with Vimeo API before we use Vimeo to host media files for our service.

I installed PyVimeo through pip and tried to run following example code provided by the author.

```
import vimeo

v = vimeo.VimeoClient(
    token=YOUR_ACCESS_TOKEN,
    key=YOUR_CLIENT_ID,
    secret=YOUR_CLIENT_SECRET)

# Make the request to the server for the "/me" endpoint.
about_me = v.get('/me')

assert about_me.status_code == 200  # Make sure we got back a successful response.
print about_me.json()   # Load the body's JSON data.
```

when I call these lines, error occurs and following trackback is shown.

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import vimeo
  File "vimeo.py", line 3, in <module>
AttributeError: 'module' object has no attribute 'VimeoClient'
```

Can anyone know how to fix this?
I think that python doesn't know where 'VimeoClient' Class in the module...

**Comment by khs8727** [comment]
nvm
